from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import UserProfileViewSet, LoginAPIView

router = DefaultRouter()

# Register the viewset to the router
router.register(r'user_profiles', UserProfileViewSet,basename="user_profiles")
router.register(r'login', LoginAPIView,basename="login")
# urlpatterns = [
#     # Login route
#     path('login/', LoginAPIView.as_view(), name='login'),
    
#     # Include the routes generated by the router
#     path('', include(router.urls)),
# ]
